name: klimakalkulator
services:
  - name: flask-app
    build:
      steps:
        - name: Install Python dependencies
          run: |
            cd server
            pip install -r requirements.txt
    ports:
      - 80
    env:
      - name: PORT
        value: "80"
    source:
      type: github
      repo: ErlendKK/klimakalkulator
      branch: main
    run:
      command: gunicorn --chdir server --bind :$PORT app:app
